name: "osv-scanner-reporter"
description: "Specialized reporting of scanner results for github actions. (Experimental)"
inputs:
  scan-args:
    description: "Arguments to osv-scanner, separated by new line"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/google/osv-scanner-action:v2.0.0"
  entrypoint: /root/osv-reporter
  args:
    - "${{ inputs.scan-args }}"